# Generated by Django 5.2.5 on 2025-10-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('bodeguero', 'bodeguero'), ('propietario', 'Supervisor'), ('gerente', 'gerente')], default='bodeguero', max_length=30),
        ),
    ]
