# Generated by Django 5.2.5 on 2025-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('bodeguero', 'bodeguero'), ('propietario', 'Supervisor'), ('gerente', 'gerente'), ('cliente', 'Cliente')], default='bodeguero', max_length=30),
        ),
    ]
