# Generated by Django 5.2.5 on 2025-09-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
