# Generated by Django 5.2.5 on 2025-11-14 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido_detallepedido_ubicacionproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='La categoría solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números, espacios y guiones.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9\\s\\-\\_]+$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor que cero.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='El stock debe ser al menos 1.')]),
        ),
    ]
