# Generated by Django 5.2.5 on 2025-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_pedido_direccion_envio_pedido_email_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
